wait for test and check completion

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -75,3 +75,16 @@ jobs:
           rm -f ~/.git-credentials
           docker stop hatchet-lite || true
           docker rm hatchet-lite || true
+
+  test-results:
+    runs-on: ubuntu-22.04
+    needs: [ tests ]
+    if: always()
+    steps:
+      - name: Check test results
+        run: |
+          if [[ "${{ needs.test.result }}" != "success" ]]; then
+            echo "Test job failed"
+            exit 1
+          fi
+          echo "All checks passed successfully!"
